version: "3"

services:  
  mysql:
    build: ./bin/mysql
    container_name: 'my-mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
    networks:
      - web-db-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'my-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
    networks:
      - web-db-net

networks:
  web-db-net:
